//! rules/mod.rs — Rule-set loading with compile-time default + runtime updates.
//
// Priority order (highest → lowest):
//  1. User-override file: $SECRETS_SCANNER_RULES env var (any path)
//  2. Cached updated file in the OS data dir (~/.local/share/secrets-scanner/ on Linux,
//     ~/Library/Application Support/secrets-scanner/ on macOS,
//     %APPDATA%\secrets-scanner\ on Windows)
//  3. Compiled-in default (assets/gitleaks.toml embedded at build time)

use log::{info, warn};

/// Core compiled rule engine (Aho-Corasick automaton + compiled regexes).
pub mod engine;

/// Compiled allowlist structures and evaluations.
pub mod allowlist;

/// TOML ruleset merging (shared between build.rs and runtime updater).
pub mod merge;

/// Rule-source manifest (`assets/sources.toml`) parsing and selection.
pub mod manifest;

/// Runtime HTTP rule updater (feature-gated: `updater`).
pub mod updater;

/// TOML rule-set validation (structure + regex compilation checks).
pub mod validation;

/// The combined ruleset compiled into the binary. Generated by build.rs into
/// `$OUT_DIR` from the manifest (lean by default; full with `--features
/// full-ruleset`). The committed `assets/secrets-scanner.toml` is the lockfile-
/// style lean artifact regenerated by `make merge-rules` for inspection/drift.
pub const BUNDLED_RULES: &str = include_str!(concat!(env!("OUT_DIR"), "/secrets-scanner.toml"));

/// The local custom ruleset compiled into the binary.
pub const BUNDLED_LOCAL_RULES: &str = include_str!("../../assets/local.toml");

/// Helper to load custom/local rules from disk, falling back to the bundled one.
#[cfg(feature = "updater")]
pub(crate) fn load_local_rules_for_merge() -> String {
    if let Ok(content) = std::fs::read_to_string("local.toml") {
        return content;
    }
    if let Ok(content) = std::fs::read_to_string("assets/local.toml") {
        return content;
    }
    if let Some(dir) = updater::data_dir() {
        let path = dir.join("local.toml");
        if let Ok(content) = std::fs::read_to_string(&path) {
            return content;
        }
    }
    BUNDLED_LOCAL_RULES.to_string()
}

/// Return the active TOML rule content as a string, following the priority
/// order documented above.  This is intentionally synchronous so callers do
/// not need an async runtime just to load rules at startup.
pub fn load_rules() -> String {
    // 1. Explicit override via environment variable
    if let Ok(path) = std::env::var("SECRETS_SCANNER_RULES") {
        match std::fs::read_to_string(&path) {
            Ok(content) => {
                info!("[rules] Using override from SECRETS_SCANNER_RULES={path}");
                return content;
            }
            Err(e) => warn!("[rules] SECRETS_SCANNER_RULES={path} unreadable: {e}"),
        }
    }

    // 2. Cached file written by the updater
    if let Some(cache_path) = updater::cached_rules_path() {
        if let Ok(content) = std::fs::read_to_string(&cache_path) {
            info!(
                "[rules] Using cached combined rules from {}",
                cache_path.display()
            );

            // Check staleness — warn if cached rules are > 7 days old
            if let Ok(metadata) = std::fs::metadata(&cache_path) {
                if let Ok(modified) = metadata.modified() {
                    if let Ok(elapsed) = modified.elapsed() {
                        let days = elapsed.as_secs() / 86400;
                        if days > 7 {
                            info!(
                                "[rules] Cached rules are {days} days old. \
                                 Run `secrets-scanner update-rules` to refresh."
                            );
                        }
                    }
                }
            }

            return content;
        } // else fall through to bundled default
    }

    // 3. Bundled default (pre-merged at build time)
    info!("[rules] Using bundled default combined rules (run `secrets-scanner update-rules` to refresh)");
    BUNDLED_RULES.to_string()
}
