//! rules/mod.rs — Rule-set loading with compile-time default + runtime updates.
//
// Priority order (highest → lowest):
//  1. User-override file: $SECRETS_SCANNER_RULES env var (any path)
//  2. Cached updated file in the OS data dir (~/.local/share/secrets-scanner/ on Linux,
//     ~/Library/Application Support/secrets-scanner/ on macOS,
//     %APPDATA%\secrets-scanner\ on Windows)
//  3. Compiled-in default (assets/gitleaks.toml embedded at build time)

use log::{info, warn};

/// Core compiled rule engine (Aho-Corasick automaton + compiled regexes).
pub mod engine;

/// Compiled allowlist structures and evaluations.
pub mod allowlist;

/// TOML ruleset merging (shared between build.rs and runtime updater).
pub mod merge;

/// Rule-source manifest (`assets/sources.toml`) parsing and selection.
pub mod manifest;

/// Runtime HTTP rule updater (feature-gated: `updater`).
pub mod updater;

/// TOML rule-set validation (structure + regex compilation checks).
pub mod validation;

/// The combined ruleset compiled into the binary. Generated by build.rs into
/// `$OUT_DIR` from the manifest (lean by default; full with `--features
/// full-ruleset`). The committed `assets/secrets-scanner.toml` is the lockfile-
/// style lean artifact regenerated by `make merge-rules` for inspection/drift.
pub const BUNDLED_RULES: &str = include_str!(concat!(env!("OUT_DIR"), "/secrets-scanner.toml"));

/// The local custom ruleset compiled into the binary.
pub const BUNDLED_LOCAL_RULES: &str = include_str!("../../assets/local.toml");

/// Helper to load custom/local rules from disk, falling back to the bundled one.
#[cfg(feature = "updater")]
pub(crate) fn load_local_rules_for_merge() -> String {
    if let Ok(content) = std::fs::read_to_string("local.toml") {
        return content;
    }
    if let Ok(content) = std::fs::read_to_string("assets/local.toml") {
        return content;
    }
    if let Some(dir) = updater::data_dir() {
        let path = dir.join("local.toml");
        if let Ok(content) = std::fs::read_to_string(&path) {
            return content;
        }
    }
    BUNDLED_LOCAL_RULES.to_string()
}

/// Return the active TOML rule content as a string, following the priority
/// order documented above.  This is intentionally synchronous so callers do
/// not need an async runtime just to load rules at startup.
pub fn load_rules() -> String {
    // 1. Explicit override via environment variable
    if let Ok(path) = std::env::var("SECRETS_SCANNER_RULES") {
        match std::fs::read_to_string(&path) {
            Ok(content) => {
                info!("[rules] Using override from SECRETS_SCANNER_RULES={path}");
                return content;
            }
            Err(e) => warn!("[rules] SECRETS_SCANNER_RULES={path} unreadable: {e}"),
        }
    }

    // 2. Cached file written by the updater
    if let Some(cache_path) = updater::cached_rules_path() {
        if let Ok(content) = std::fs::read_to_string(&cache_path) {
            match validation::validate_rules_toml(&content) {
                Ok(()) => {
                    info!(
                        "[rules] Using cached combined rules from {}",
                        cache_path.display()
                    );

                    // Check staleness — warn if cached rules are > 7 days old
                    if let Ok(metadata) = std::fs::metadata(&cache_path) {
                        if let Ok(modified) = metadata.modified() {
                            if let Ok(elapsed) = modified.elapsed() {
                                let days = elapsed.as_secs() / 86400;
                                if days > 7 {
                                    info!(
                                        "[rules] Cached rules are {days} days old. \
                                         Run `secrets-scanner update-rules` to refresh."
                                    );
                                }
                            }
                        }
                    }

                    return content;
                }
                Err(errors) => {
                    warn!(
                        "[rules] Cached combined rules at {} are invalid; falling back to bundled rules:\n- {}",
                        cache_path.display(),
                        errors.join("\n- ")
                    );
                }
            }
        } // else fall through to bundled default
    }

    // 3. Bundled default (pre-merged at build time)
    info!("[rules] Using bundled default combined rules (run `secrets-scanner update-rules` to refresh)");
    BUNDLED_RULES.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsString;
    use std::sync::{Mutex, OnceLock};

    fn env_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    struct EnvGuard {
        home: Option<OsString>,
        rules: Option<OsString>,
    }

    impl EnvGuard {
        fn capture() -> Self {
            Self {
                home: std::env::var_os("HOME"),
                rules: std::env::var_os("SECRETS_SCANNER_RULES"),
            }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            match &self.home {
                Some(home) => std::env::set_var("HOME", home),
                None => std::env::remove_var("HOME"),
            }
            match &self.rules {
                Some(rules) => std::env::set_var("SECRETS_SCANNER_RULES", rules),
                None => std::env::remove_var("SECRETS_SCANNER_RULES"),
            }
        }
    }

    #[test]
    fn invalid_cached_rules_fall_back_to_bundled_rules() {
        let _lock = env_lock().lock().expect("env lock");
        let _guard = EnvGuard::capture();
        let temp_home = tempfile::tempdir().expect("temp home");
        std::env::set_var("HOME", temp_home.path());
        std::env::remove_var("SECRETS_SCANNER_RULES");

        let cache_path = updater::cached_rules_path().expect("cache path");
        std::fs::create_dir_all(cache_path.parent().expect("cache parent")).expect("cache dir");
        std::fs::write(&cache_path, "not valid toml = [").expect("write invalid cache");

        assert_eq!(load_rules(), BUNDLED_RULES);
    }

    #[test]
    fn explicit_invalid_rules_override_still_errors() {
        let _lock = env_lock().lock().expect("env lock");
        let _guard = EnvGuard::capture();
        let temp_home = tempfile::tempdir().expect("temp home");
        let temp_rules = tempfile::NamedTempFile::new().expect("temp rules");
        std::env::set_var("HOME", temp_home.path());
        std::fs::write(temp_rules.path(), "not valid toml = [").expect("write invalid rules");
        std::env::set_var("SECRETS_SCANNER_RULES", temp_rules.path());

        assert!(crate::Scanner::new().is_err());
    }
}
