// build.rs — Generate the embedded ruleset at compile time.
//
// Reads the source manifest (assets/sources.toml), selects the sources to embed
// (all `embed = true`, plus `embed = false` ones when built with
// `--features full-ruleset`), validates and merges them via the shared
// `merge_sources` core, and writes the combined ruleset to `$OUT_DIR` for
// `include_str!` in src/rules/mod.rs.
//
// We write to OUT_DIR (not the committed assets/secrets-scanner.toml) so a
// `--features full-ruleset` build never pollutes the working tree, and the lean
// and full builds don't fight over a single file. The committed
// assets/secrets-scanner.toml is a lockfile-style artifact regenerated by
// `make merge-rules`, which calls the SAME `merge_sources` core — so it stays
// byte-identical to a lean build (verified by the CI drift check).

use std::path::{Path, PathBuf};

#[path = "src/rules/validation.rs"]
mod validation;

#[path = "src/rules/merge.rs"]
mod merge;

#[path = "src/rules/manifest.rs"]
mod manifest;

/// Minimal valid placeholder written when an embedded source file is missing,
/// so a fresh checkout (before `scripts/update_rules.sh`) still builds.
const PLACEHOLDER_TOML: &str = "title = \"placeholder\"\n\nrules = []\n";

fn main() {
    let manifest_path = Path::new("assets/sources.toml");
    // Embedded ruleset is written to OUT_DIR (per-build), not the committed asset.
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let combined_path = out_dir.join("secrets-scanner.toml");
    let combined_path = combined_path.as_path();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=assets/sources.toml");

    // Manifest missing → fall back to the legacy gitleaks + local 2-way merge.
    if !manifest_path.exists() {
        println!("cargo:warning=assets/sources.toml not found; using legacy gitleaks+local merge.");
        legacy_merge(combined_path);
        return;
    }

    let manifest_src = std::fs::read_to_string(manifest_path).expect("read assets/sources.toml");
    let manifest = manifest::parse_manifest(&manifest_src).expect("parse assets/sources.toml");

    // Cargo sets CARGO_FEATURE_<NAME> (upper-cased, '-' → '_') for enabled features
    // when running the build script. This is how build.rs learns about features.
    let full = std::env::var_os("CARGO_FEATURE_FULL_RULESET").is_some();
    // Only announce the non-default (opt-in) full build; stay quiet for lean so a
    // normal `cargo build` produces no spurious warnings.
    if full {
        println!("cargo:warning=secrets-scanner: embedding FULL ruleset (gitleaks+local+spdb)");
    }

    let selected = manifest::select_sources(
        &manifest,
        &manifest::SelectOptions {
            include_embed_false: full,
        },
    );

    // Rebuild when any listed source file changes — selected or not — so toggling
    // the feature or editing a not-yet-embedded source triggers a recompile.
    for src in &manifest.sources {
        println!("cargo:rerun-if-changed={}", src.file);
    }

    let mut merge_inputs = Vec::new();
    for src in &selected {
        // Deferred sources without a TOML converter (e.g. kingfisher YAML) are
        // skipped until a converter exists; they stay declared in the manifest.
        if !src.file.ends_with(".toml") {
            println!(
                "cargo:warning=skipping non-TOML source '{}' ({}): no converter yet",
                src.name, src.file
            );
            continue;
        }

        let content = match std::fs::read_to_string(&src.file) {
            Ok(c) => c,
            Err(_) if src.embed => {
                // Keep the build resilient: write a valid empty placeholder.
                println!(
                    "cargo:warning=embedded source '{}' missing ({}); using empty placeholder.",
                    src.name, src.file
                );
                if let Some(parent) = Path::new(&src.file).parent() {
                    let _ = std::fs::create_dir_all(parent);
                }
                let _ = std::fs::write(&src.file, PLACEHOLDER_TOML);
                PLACEHOLDER_TOML.to_string()
            }
            Err(_) => {
                println!(
                    "cargo:warning=optional source '{}' missing ({}); skipping.",
                    src.name, src.file
                );
                continue;
            }
        };

        if let Err(errors) = validation::validate_rules_toml(&content) {
            panic!(
                "assets source '{}' is invalid:\n- {}",
                src.name,
                errors.join("\n- ")
            );
        }

        merge_inputs.push(merge::MergeSource {
            name: src.name.clone(),
            priority: src.priority,
            toml: content,
        });
    }

    let (combined, _report) =
        merge::merge_sources(merge_inputs).expect("merge manifest sources at compile time");

    if let Err(errors) = validation::validate_rules_toml(&combined) {
        panic!(
            "Merged assets/secrets-scanner.toml is invalid:\n- {}",
            errors.join("\n- ")
        );
    }

    std::fs::write(combined_path, combined).expect("write OUT_DIR/secrets-scanner.toml");
}

/// Legacy 2-way merge of gitleaks.toml + local.toml, used only when the manifest
/// is absent. Mirrors the historical build behaviour, including placeholders.
fn legacy_merge(combined_path: &Path) {
    let gitleaks_path = Path::new("assets/gitleaks.toml");
    let local_path = Path::new("assets/local.toml");

    if !gitleaks_path.exists() {
        eprintln!(
            "cargo:warning=assets/gitleaks.toml not found. \
             Run `./scripts/update_rules.sh` to download it."
        );
        std::fs::create_dir_all("assets").expect("create assets/");
        std::fs::write(gitleaks_path, "# placeholder — run update_rules.sh\n")
            .expect("write placeholder gitleaks.toml");
    }
    if !local_path.exists() {
        std::fs::create_dir_all("assets").expect("create assets/");
        std::fs::write(local_path, "title = \"local rules\"\n\nrules = []\n")
            .expect("write placeholder local.toml");
    }

    let gitleaks_content = std::fs::read_to_string(gitleaks_path).expect("read gitleaks.toml");
    let local_content = std::fs::read_to_string(local_path).expect("read local.toml");

    if let Err(errors) = validation::validate_rules_toml(&gitleaks_content) {
        panic!(
            "assets/gitleaks.toml is invalid:\n- {}",
            errors.join("\n- ")
        );
    }
    if let Err(errors) = validation::validate_rules_toml(&local_content) {
        panic!("assets/local.toml is invalid:\n- {}", errors.join("\n- "));
    }

    match merge::merge_toml_rules(&gitleaks_content, &local_content) {
        Ok(combined) => {
            if let Err(errors) = validation::validate_rules_toml(&combined) {
                panic!(
                    "Merged assets/secrets-scanner.toml is invalid:\n- {}",
                    errors.join("\n- ")
                );
            }
            std::fs::write(combined_path, combined).expect("write secrets-scanner.toml");
        }
        Err(e) => panic!("Failed to merge rules at compile time: {e}"),
    }

    println!("cargo:rerun-if-changed=assets/gitleaks.toml");
    println!("cargo:rerun-if-changed=assets/local.toml");
}
